setopt CORRECT
setopt EXTENDED_GLOB
setopt AUTO_PUSHD
setopt PUSHD_IGNORE_DUPS

# History

HISTSIZE=20000
SAVEHIST=20000
HISTFILE=~/.zsh_history

setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_REDUCE_BLANKS

# Completion

fpath=(~/.zsh/completions $fpath)
autoload -Uz compinit
compinit

zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache

# Colors

export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad

# Commands

alias ls='ls -G'
alias ll='ls -lah'

# Prompt

autoload -U colors && colors
setopt PROMPT_SUBST

PROMPT='%F{cyan}%n@%m%f %F{yellow}%~%f %# '

# Key bindings

bindkey '^[[H' beginning-of-line
bindkey '^[[F' end-of-line
bindkey '^R' history-incremental-search-backward

# Environment

export GOPATH="$HOME/.go"
export PATH="$GOPATH/bin:$HOME/.local/bin:$PATH"
